(facelets_element) @framework.facelets
(jsf_html_element) @framework.jsf_html
(jsf_core_element) @framework.jsf_core
(composite_component_element) @framework.composite
(faces_element) @framework.html_friendly
(primefaces_element) @framework.primefaces
(primefaces_extensions_element) @framework.primefaces_extensions
(jstl_element) @framework.jstl
(qualified_element) @framework.qualified
(xml_element) @framework.xml
(faces_attribute) @attribute.faces
(passthrough_attribute) @attribute.passthrough
(deferred_expression) @el.deferred
(immediate_expression) @el.immediate
(el_function_call) @el.function
(el_lambda_expression) @el.lambda
(el_map_or_set_literal) @el.map_or_set
(el_list_literal) @el.list
(ERROR) @diagnostic.error
